// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AccessoriesInputController from "./accessories_input_controller"
application.register("accessories-input", AccessoriesInputController)

import AutocompleteController from "./autocomplete_controller"
application.register("autocomplete", AutocompleteController)

import DatepickerController from "./datepicker_controller"
application.register("datepicker", DatepickerController)

import DeptsSelectorController from "./depts_selector_controller"
application.register("depts-selector", DeptsSelectorController)

import FilterDropdownController from "./filter_dropdown_controller"
application.register("filter-dropdown", FilterDropdownController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import FormValidationController from "./form_validation_controller"
application.register("form-validation", FormValidationController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import InlineTabsController from "./inline_tabs_controller"
application.register("inline-tabs", InlineTabsController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import OrderController from "./order_controller"
application.register("order", OrderController)

import PaginationController from "./pagination_controller"
application.register("pagination", PaginationController)

import ParentItemEditFormController from "./parent_item_edit_form_controller"
application.register("parent-item-edit-form", ParentItemEditFormController)

import ReadmoreController from "./readmore_controller"
application.register("readmore", ReadmoreController)

import ShowDetailsController from "./show_details_controller"
application.register("show-details", ShowDetailsController)

import SidebarCartController from "./sidebar_cart_controller"
application.register("sidebar-cart", SidebarCartController)

import StudentIdInputController from "./student_id_input_controller"
application.register("student-id-input", StudentIdInputController)

import TagsInputController from "./tags_input_controller"
application.register("tags-input", TagsInputController)

import TimeagoController from "./timeago_controller"
application.register("timeago", TimeagoController)

import UniqueItemsController from "./unique_items_controller"
application.register("unique-items", UniqueItemsController)

import VersionSelectController from "./version_select_controller"
application.register("version-select", VersionSelectController)
